import React from "react";
import Head from "next/head";
import LoginRedirect from "../../../../components/RedirectLogin";

const RedirectPage = () => {
  return (
    <div>
      <Head>
        <title>SignUp - Vercel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginRedirect />
    </div>
  );
};

export default RedirectPage;
