import Head from "next/head";
import React from "react";
import SignUp from "../../components/SignUp";
import { useRouter } from "next/router";

const SignUpPage = () => {
  // const [userData, setUserData]: any = React.useState();

  // React.useEffect(() => {
  //   const fetchAuthenticatedUser = async () => {
  //     const accessToken = localStorage.getItem("accesstoken");

  //     const response = await fetch(`https://api.github.com/user`, {
  //       headers: { Authorization: `Bearer ${accessToken}` },
  //     });
  //     const data = await response.json();

  //     setUserData(data);
  //   };

  //   console.log(userData);

  //   fetchAuthenticatedUser();
  // });

  const router = useRouter();

  React.useEffect(() => {
    const userData = localStorage.getItem("username");

    console.log(userData);
    if (userData) router.push("/dashboard");
  }, [router]);

  return (
    <div>
      <Head>
        <title>SignUp - Vercel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SignUp />
    </div>
  );
};

export default SignUpPage;
