import React from "react";
import { useRouter } from "next/router";

// import { ChevronDownIcon, ChevronUpIcon } from "@chakra-ui/icons";
// import {
//   Box,
//   Button,
//   Container,
//   HStack,
//   Image,
//   Spacer,
//   Text,
//   VStack,
// } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const router = useRouter();
  // const [show, setShow] = React.useState(false);

  React.useEffect(() => {
    router.push("/dashboard");
  });

  return (
    <div>
      <Head>
        <title>Vercel | Deploy Your Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Container
        maxW={{ lg: "container.lg", sm: "container.sm", md: "container.md" }}
      >
        <VStack w="100%" alignItems="stretch" m={3} borderColor="gray.300">
          <HStack spacing={5}>
            <Image src="/vercel.svg" alt="Vercel" boxSize="100px" />
            <Spacer />
            <Text
              onClick={() => {
                setShow(!show);
              }}
              cursor="pointer"
              color="gray.500"
              _hover={{ color: "gray.600" }}
            >
              Features
              {show ? <ChevronUpIcon /> : <ChevronDownIcon />}
            </Text>
            <Text>Features</Text>
            <Text>Features</Text>
            <Text>Features</Text>
            <Text>Features</Text>
            <Spacer />
            <Text>Features</Text>
            <Text>Features</Text>
            <Button colorScheme="teal" variant="solid" px={4}>
              Sign Up
            </Button>
          </HStack>
          <HStack>
            {show && (
              <VStack>
                <HStack spacing={5}>
                  <Box
                    bg="white"
                    p={4}
                    color="black"
                    _hover={{
                      bgColor: "gray.100",
                    }}
                  >
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Distinctio, accusantium.
                  </Box>
                  <Box
                    bg="white"
                    p={4}
                    color="black"
                    _hover={{
                      bgColor: "gray.100",
                    }}
                  >
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Ipsum esse eveniet totam quae, deleniti voluptate?
                  </Box>
                  <Box
                    bg="white"
                    p={4}
                    color="black"
                    _hover={{
                      bgColor: "gray.100",
                    }}
                  >
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Minus officia repellat harum modi nobis dolor quos numquam!
                  </Box>
                </HStack>
                <HStack>
                  <Text>2nd Row</Text>
                </HStack>
              </VStack>
            )}
            {!show && <Text>Not Show Card</Text>}
          </HStack>
        </VStack>
      </Container> */}
    </div>
  );
};

export default Home;
