import Head from "next/head";
import React from "react";
import Dashboard from "../../components/Dashboard";

const DashboardPage = () => {
  return (
    <div>
      <Head>
        <title>Vercel | Deploy Your Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard />
    </div>
  );
};

export default DashboardPage;
