import Head from "next/head";
import React from "react";
import CreateProject from "../../components/CreateProject";

const CreateProjectPage = () => {
  return (
    <div>
      <Head>
        <title>New Project - Vercel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CreateProject />
    </div>
  );
};

export default CreateProjectPage;
